export const transactionCategories = [
  "income",
  "transfer",
  "rent & utilities",
  "food & drink",
  "groceries",
  "transportation",
  "shopping",
  "entertainment",
  "health & wellness",
  "insurance",
  "loan payment",
  "subscriptions",
  "travel",
  "education",
  "personal care",
  "charitable",
  "other",
  "uncategorized",
];
